apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-deployment
  namespace: uat  # Namespace for UAT
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
        - name: task-tracker-app
          image: brittajaison/task-tracker-app:latest
          ports:
            - containerPort: 3000  # Ensure this matches the service targetPort
