apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-deployment
  namespace: prd  # Namespace for Production
spec:
  replicas: 2  # Increase replicas for production if needed
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      automountServiceAccountToken: false  # Move this here at the pod level
      containers:
        - name: task-tracker-app
          image: nusissgroup6/task-tracker-app:4e2e741e0c3227aceb176c2e4aa451af9262d408
          imagePullPolicy: Always
          resources:
            requests:
              ephemeral-storage: "1Gi"  # Minimum storage requested
              memory: "512Mi"           # Minimum memory requested
            limits:

              ephemeral-storage: "2Gi"  # Maximum storage limit
              memory: "1Gi"             # Maximum memory limit

            


          ports:
            - containerPort: 3000  # Ensure this matches the service targetPorts
