apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-deployment
  namespace: prod  # Namespace for Production
spec:
  replicas: 3  # Increase replicas for production if needed
  selector:
    matchLabels:
      app: task-tracker-app
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
        - name: task-tracker-app
          image: brittajaison/task-tracker-app:latest
        automountServiceAccountToken: false
        resources:
          limits:
            ephemeral-storage: "2Gi"
          ports:
            - containerPort: 3000  # Ensure this matches the service targetPort
