apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-app-uat-deployment
  namespace: uat  # Namespace for UAT
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-tracker-app-uat
  template:
    metadata:
      labels:
        app: task-tracker-app-uat
    spec:
      automountServiceAccountToken: false
      containers:
        - name: task-tracker-app-uat
          image: nusissgroup6/task-tracker-app-uat:latest
          resources:
          limits:
            ephemeral-storage: "2Gi"
          ports:
            - containerPort: 3000  # Ensure this matches the service targetPort
