apiVersion: v1
kind: Service
metadata:
  name: task-tracker-app-service
spec:
  selector:
    app: task-tracker-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
