name: prd_deploy
on:
  # trigger for CI
  workflow_dispatch:
  # This workflow is automatically triggered upon a push request to the development branch. 
  # The test-build : indicating whether your code commits are not breaking during compilation.
  # The unit-test : indicating whether your functionalities are not breaking.
  # The Sonar : indicating whether your code commits are not violating code scan rules.
  ##
  #push:
  #  branches:
  #    - mainx
  #  paths-ignore:
  #    - '.github/**'
  #    - 'public/**'
  #    - 'README.md' 
  #    - 'sonar-project.properties' 
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]     
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with: 
          ref: main
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - run: npm ci
      
      - run: npm run build --if-present
      
      - run: CI=true npm test

  code_scan:
    needs: test_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Analyze on SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     

  

  build_docker_image:
    needs: code_scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          # Log in to Docker Hub using the username and password stored in GitHub Secrets
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          
          # Build and push the Docker image for multiple platforms (e.g., amd64 and arm64)
          docker buildx build --platform linux/amd64,linux/arm64 -t $DOCKER_USERNAME/task-tracker-app-prd:latest --push .
        
